### ISSUE TITLE
Issues compiling with gcc 5

### ISSUE THREAD

**Issue by mwerski** [envy/knx2influx#15]
Building under CentOS7 with gcc 4.8.5 is working fine, but compiling under Ubuntu 16 with a gcc 5.4.0 does not work because the libs to link against are given in the wrong order.
After changing line 9 in the Makefile from
`8	knx2influx: knx2influx.o cJSON.o config.o libknxnet/libknxnet.a`
`9		$(CXX)  $(LDFLAGS) $^ -o $@`
to
`8	knx2influx: knx2influx.o cJSON.o config.o libknxnet/libknxnet.a`
`9		$(CXX) $^ -o $@ $(LDFLAGS)`
knx2influx compiles under both gcc versions without further problems.

**Comment by envy** [comment]
Funny, on my Debian 8 with gcc 6.3.0 it compiled fine :D
