### ISSUE TITLE
JSON error: No interface given in config

### ISSUE THREAD

**Issue by handelaar2** [envy/knx2influx#18]
When I start knx2influx, I get the error message:
JSON error: No interface given in config!
Error parsing JSON.

How (which format) do I add the interface to knx2influx.json
Im confused as nothing about the interface is mentioned in the config json.
My current json file has the minimal config:
{
  "host": "http://localhost:8086",
  "database": "knx",
  "gas": []
}

**Comment by envy** [comment]
Hi,

sorry, I need to update the readme.
You need to specify the IP address of the interface knx2influx should listen on for multicast traffic like so:
```json
{
"host": "http://localhost:8086",
"interface": "192.168.0.100",
"database": "knx",
"gas": []
}
```

Replace 192.168.0.100 with the IP address of your interface.

**Comment by handelaar2** [comment]
That got me a step further. Danke.

Now I get the following error:
Sending data to http://localhost:8086 database knx
Error adding membership: No such device
terminate called after throwing an instance of 'std::exception*'
Aborted (core dumped)

Any suggestions?
I wonder if the influx database is created automatically. Do I need to do something in influx?

**Comment by envy** [comment]
Which IP did you put in?
"No such device" means that it could not find an interface with that IP.
Do not put the IP of your KNX router there but the IP of the PC/VM running knx2influx.

**Comment by handelaar2** [comment]
That did the trick. Now it says:
Sending data to http://localhost:8086 database knx

Running the command "SHOW DATABASES" in influx, I only see the '_internal' database and no knx. Do I need to build the database in influx (how?). Vielen Dank!

**Comment by envy** [comment]
The database should be created on first insert, you can [create it manually](https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#create-database).

If nothing it inserted, then knx2influx is not seeing any data.
Make sure that
1. you actually use a KNX router and *not* an interface
2. the filter table on your router is configured correctly to let KNX telegrams into your network
3. knx2influx is configured to listen to specific GAs. If no GAs are configured, knx2influx will not listen for anything.

**Comment by handelaar2** [comment]
Ok. It is working now. I was confused by "minimal configuration" . As you mention in point 3, one must set up the GAs. 
(which makes sense as it needs conversion (e.g. dtp=9) and it also writes the tag-info  to Influx)

I also needed to create the database and therefore executed the following command in influx:
CREATE DATABASE "knx"

Now the output of the program looks good and shows:
Sending data to http://localhost:8086 database knx
temp,sender=1.1.230,room=Living value=21.740000
temp,sender=1.1.33,room=Living value=21.719999
temp,sender=1.1.230,room=Living value=21.719999
temp,sender=1.1.33,room=Living value=21.740000
temp,sender=1.1.230,room=Living value=21.740000
temp,sender=1.1.33,room=Living value=21.740000
.....

And this is how it looks in Grafana :-) :
<img width="1270" alt="Screenshot 2019-12-09 at 16 10 49" src="https://user-images.githubusercontent.com/28559038/70447146-924e9580-1a9e-11ea-8e30-c64ae866ef78.png">

Thanks for your help!!!!!!!!!!
