### ISSUE TITLE
make on macOS fails: error: unknown type name 'pthread_barrier_t'

### ISSUE THREAD

**Issue by handelaar2** [envy/knx2influx#20]
Hi Envy,
I triedto compile knx2influx on a mac (macOS Catalina 10.15.1).
I get however the following error:  **unknown type name 'pthread_barrier_t'**
I tried to compile with different -std options, but the error did not disappear.
Would you know a way of successfully compiling knx2influx on a mac?

make:
c++ -O0 -g -I. -I./libknxnet -Wall -fpie -fstack-protector-strong -std=c++11 -c -o knx2influx.o knx2influx.cpp
knx2influx.cpp:28:8: error: unknown type name 'pthread_barrier_t'
static pthread_barrier_t bar;
       ^
1 error generated.
make: *** [knx2influx.o] Error 1

Not sure how to implement this:
https://blog.albertarmea.com/post/47089939939/using-pthreadbarrier-on-mac-os-x

**Comment by envy** [comment]
Hi,

macOS does not have pthread barriers so it won't compile.

I might change it so it uses something else because in my case I only use it to make the main thread wait for the reader thread.

You can try one of the many pthread barrier implementations for macOS but I don't know if they will work.

**Comment by envy** [comment]
Should be fixed now.

**Comment by MarouanDoulahiane** [comment]
to fix the issue you must add this macro before includes
```c
#define _XOPEN_SOURCE 600
```

like this :
```c
#define _XOPEN_SOURCE 600
#include <stdlib.h>
#include <stdio.h>
#define _XOPEN_SOURCE 600 
#include <pthread.h>
#include <unistd.h>

pthread_barrier_t	barrier;
```
