### ISSUE TITLE
no such device

### ISSUE THREAD

**Issue by ferengi82** [envy/knx2influx#21]
Hallo,

ich wollte dein tool ausprobieren, bekomme aber immer die Meldung

```
Sending data to http://10.0.150.165:8086 database knx
Error adding membership: No such device
terminate called after throwing an instance of 'std::exception*'
Aborted
```

meine config sieht grad so aus (nur eine GA zum testen)

```
{
        "interface": "10.0.150.151",
        "host": "http://10.0.150.165:8086",
        "database": "knx",
        "gas":
        [
                {
                        "ga": "0/5/104",
                        "ignored_senders": ["1.1.253"],
                        "series": "energie",
                        "dpt": 14
                }
        ]
}
```

Die verbindung zum DB-Server scheint zu funktionieren

```
curl -G http://10.0.150.165:8086/query --data-urlencode "q=SHOW DATABASES"
{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["_internal"],["edomi"],["iobroker"],["collectd"],["plex_data"],["proxmox"],["knx"]]}]}]}
```

Interface hab ich über EIBD / KNXD, und direkt auf die IP-Schnittstelle/Router probiert. Der fehler bleibt der gleiche.

Hast du irgend welche Tipps für mich?

Gruß
Christian

**Comment by envy** [comment]
Hi,

bei `interface` kommt nicht die IP des KNX Routers rein sondern die IP des Netzwerkinterfaces auf dem knx2influx lauschen soll, also die IP des Hosts auf dem knx2influx läuft.

**Comment by ferengi82** [comment]
Danke, da hätt ich auch selber drauf kommen können...
